### ISSUE TITLE
Provider doesn't work with private cloud installs

### ISSUE THREAD

**Issue by alaslums** [terraform-providers/terraform-provider-triton#109]
Hi,

So we're attempting to use the Triton terraform provider with a private cloud install, and it is bailing out attempting to parse the datacenter URL:

* data.triton_network.public: data.triton_network.public: error creating Network client: Error Creating Triton Network Client: invalid data center in URL: failed to parse datacenter from 'https://cloudapi.eu-staff-1.cns.everycity.com'

Reading the code (although I'm no expert at Go) it seems the provider assumes it will only be used with the following URLs:

        knownDCFormats = []string{
                `https?://(.*).api.joyent.com`,
                `https?://(.*).api.joyentcloud.com`,
                `https?://(.*).api.samsungcloud.io`,
        }

Doh?

**Comment by stack72** [comment]
Hi @alaslums 

We are looking into this immediately - we will update ASAP

Paul

**Comment by cheapRoc** [comment]
> Doh?

**Comment by stack72** [comment]
@alaslums we just made the provider release 0.5.1 that fixes this issue

Please feel free to ping us again if there is an issue

P.

**Comment by alaslums** [comment]
Amazing - thanks everyone for the speedy response, much appreciated!
