### ISSUE TITLE
Datacenter resource fails with confusing error when using joyentcloud.com URLs

### ISSUE THREAD

**Issue by SamWhited** [terraform-providers/terraform-provider-triton#116]
### Terraform Version

```
terraform -version
Terraform v0.11.7
+ provider.triton v0.5.1
```

### Affected Resource(s)

- triton_datacenter

See linked issue for more information. The TL;DR is that triton_datacenter doesn't work if you're using an old joyentcloud.com URL.

### Important Factoids

I believe the issue is here:

https://github.com/terraform-providers/terraform-provider-triton/blob/f788f1a805ac15a22c3702bbb0c91e487b999630/triton/data_source_datacenter.go#L54

Because the old URL is no longer used, it probably isn't in the datacenter list and therefore we can't replace it. Instead the replacement should probably be:

```go
if dc.URL == tritonURL || strings.Replace(tritonURL, "joyentcloud.com", "joyent.com", -1) == dc.URL {
```

but I haven't tested this.
Also, the error message is really bad and could probably be improved (see the linked issue below).
If they've turned this domain off finally (I didn't check, sorry, I stopped debugging when I found out the new URLs fixed it), it may be worth removing this hack entirely and just fixing the error message.

Thanks!

### References

- hashicorp/terraform#18623

**Comment by twhiteman** [comment]
Thanks - this should be fixed in the latest change (upgrade to terraform v0.12.10 f1f9f75)
