### ISSUE TITLE
Update provider for terraform 0.12 

### ISSUE THREAD

**Issue by teutat3s** [terraform-providers/terraform-provider-triton#127]
Hey,

I'm trying to use this provider with the latest version of terraform (v0.12.3) but the provider plugin needs to be updated to make it work with this version. Thought it would be a good idea to have this issue to track progress and to discuss problems. Thanks everyone involved for the nice work!

https://www.terraform.io/docs/extend/terraform-0.12-compatibility.html

Terraform Version 0.12.3

### Affected Resource(s)
terraform-provider-triton

### Debug Output
https://gist.github.com/Teutone/ba36fd1c12012465a0e60fd28294c1bd

### Steps to Reproduce
1.  install terraform v0.12.3
2. add triton as provider
2. `terraform init`

**Comment by twhiteman** [comment]
It seems pull #121 (switch to go modules) will solve this.
