### ISSUE TITLE
sdc-volapi support 

### ISSUE THREAD

**Issue by neuroserve** [terraform-providers/terraform-provider-triton#131]
It would be nice, if the terraform provider for triton would support
sdc-volapi (https://github.com/joyent/sdc-volapi) in order to be able to create volumes via terraform and to extend the triton_machine resource to create volumes which are automatically mounted to machines at the required mountpoint.

**Comment by twhiteman** [comment]
Done (and released) in v0.7.0 of the Triton Terraform provider.

Volumes data sources (find):
https://www.terraform.io/docs/providers/triton/d/triton_volume.html

Volumes resources (create/update/delete):
https://www.terraform.io/docs/providers/triton/r/triton_volume.html

Machine volumes (attaching volumes to a machine) - which can only be done on create:
https://www.terraform.io/docs/providers/triton/r/triton_machine.html#example-usages
https://www.terraform.io/docs/providers/triton/r/triton_machine.html#volume
https://www.terraform.io/docs/providers/triton/r/triton_machine.html#volume-map
