### ISSUE TITLE
Add a triton_package resource

### ISSUE THREAD

**Issue by benjamin-bergia** [terraform-providers/terraform-provider-triton#16]
I am running Triton on-premises and a new resource to manage packages via terraform would be a great addition. Having to manage packages manually on the AdminUI when most of our Zones are managed via Terraform is pretty annoying.

I noticed that, for some reasons, the [CloudAPI](https://apidocs.joyent.com/cloudapi/#packages-2) doesn't seem to allow package creation. So I don't know if a triton_package resource is doable or not.

**Comment by cheapRoc** [comment]
This is a feature request for [joyent/sdc-cloudapi](https://github.com/joyent/sdc-cloudapi) and not a feature that the Terraform provider can take advantage of.

The private backend service that facilitates packages, [joyent/sdc-papi](https://github.com/joyent/sdc-papi), does not contain the proper API guarantees to be made available through the public API. The behavior of creating packages simply isn't geared toward public use cases or the security model that administers CloudAPI.

You can certainly create non-Terraform automation around the private API yourself, and there is [documentation to do so](https://docs.joyent.com/private-cloud/packages/configuring#creating-a-package). Warning though, there are no authentication mechanisms for that API and you'll have to handle that yourself accordingly.

**Comment by benjamin-bergia** [comment]
@cheapRoc understood, thank you for the explanation.

Looks like there is nothing to be done here. I will close this issue
