### ISSUE TITLE
`triton_image` needs to learn to optionally distinguish the latest in the face of several matches

### ISSUE THREAD

**Issue by jen20** [terraform-providers/terraform-provider-triton#18]
Similar to AWS, we should implement `most_recent` flag for `triton_image` for situations where conflicting versions and names are present for an image.

**Comment by cheapRoc** [comment]
This has hit me as well so I know exactly the situations with Triton in which this would be handy.

**Comment by stack72** [comment]
@jen20 / @cheapRoc PR coming for this :) I just added the functionality and am running the acceptance tests to make sure it works
