### ISSUE TITLE
Support SHA256 key identifier format

### ISSUE THREAD

**Issue by bahamat** [terraform-providers/terraform-provider-triton#33]
### Terraform Version

0.10.4

### Affected Resource(s)

triton_key

### Terraform Configuration Files
```hcl
provider "triton" {
}
```

### Debug Output

```
Error refreshing state: 1 error(s) occurred:

* provider.triton: Error Creating SSH Agent Signer: No key in the SSH Agent matches fingerprint: SHA256:l1JcBkX5QbhfTeOI6RHriundohl/MXoZPlsgE+PVlPg
```

### Expected Behavior

Support SHA256 key identifiers

### Actual Behavior

Error

### Steps to Reproduce

1. `terraform plan`

**Comment by cheapRoc** [comment]
Ref: joyent/triton-go#18
