### ISSUE TITLE
Add Internal Acceptance Testing infrastructure

### ISSUE THREAD

**Issue by stack72** [terraform-providers/terraform-provider-triton#48]
This will allow us to test unreleased features against our own specific cloud endpoints :)

**Comment by cheapRoc** [comment]
Not sure if you are aware but make sure any test account you use has the `us-east-3b` DC enabled (ping ~customer in MM). We never needed to switch HC's nightly testing account to `us-east-3b` for the affinity release but we'll want to target that DC for our own stuff. `us-east-3b` is deployed nightly and, from my own testing, any account replication lag across DCs is minimal.

**Comment by stack72** [comment]
We now have a TeamCity server up and running for our infrastructure
