### ISSUE TITLE
Add support for creating Triton Sub Users, Policies and Roles

### ISSUE THREAD

**Issue by stack72** [terraform-providers/terraform-provider-triton#57]
https://docs.joyent.com/public-cloud/rbac/users

**Comment by misterbisson** [comment]
I would shelve this and https://github.com/terraform-providers/terraform-provider-triton/issues/55 for the reasons described in https://github.com/terraform-providers/terraform-provider-triton/issues/55#issuecomment-343581296

**Comment by cheapRoc** [comment]
I also vote for keeping whatever partial upstream functionality we had in `triton-go` instead of removing it.

**Comment by stack72** [comment]
ok folks, I am going to hold off on these changes to Terraform until we decide we need them going forward

I have a working branch of a users set of functionality so I will push that to my remote for future

**Comment by stack72** [comment]
Hi @smithx10

Apologies, unfortunately I don’t work on any joyent projects anymore. FYI, the reason this was never finished is because there needed to be a small feature added to triton to have a timestamp or a status to show that an action was complete

I’m not sure what the status of that is because it’s been a while so this would be an avenue to check up on

If I find the branch, I can send you the git ref

Paul
