### ISSUE TITLE
Terraform >= 0.9.5 Triton provider doesn't work with an SSH agent anymore

### ISSUE THREAD

**Issue by siepkes** [terraform-providers/terraform-provider-triton#6]
There seems to be a regression in Terraform 0.9.5 and higher which prevents you from using an SSH agent with the Triton provider. 

I updated from Terraform 0.9.3 to 0.9.11 on CentOS 7 and couldn't get the Triton provider to work with an SSH agent anymore. I got the following error:

```
* provider.triton: Error Creating SSH Private Key Signer: Error PEM-decoding private key material: nil block received
```

I've tested also tested 0.9.4 which works fine but the issue starts at 0.9.5. I can't find anything in the changelog of 0.9.5 which says there is a change in behavior or something that could otherwise explain the behavior i'm seeing.

Normally I use an SSH agent so my Triton provider config looks like:

```
provider "triton" {
    # 'key_material' omitted on purpose so the SSH agent is used.
    account      = "<ACOUNT_NAME>"
    key_id       = "<FINGERPRINT>"
    url          = "<INTERNAL CLOUD API URL>"
}
```
The following config without an SSH agent works:

```
provider "triton" {
    key_material = "${file("/home/siepkes/.ssh/id_rsa-unec")}"
    account      = "<ACOUNT_NAME>"
    key_id       = "<FINGERPRINT>"
    url          = "<INTERNAL CLOUD API URL>"
}
```

Personally for me this is a big deal since I'm not really comfortable with having an unencrypted sitting on my disk.

**Comment by jen20** [comment]
@siepkes this is definitely a bug, though I'm not quite sure where, since all is good with my using an SSH agent from `master` builds of this provider. Let me take a look...

**Comment by jen20** [comment]
Hi @siepkes, is this problem still persisting? I cannot reproduce it here with any type of SSH key. It looks to me like this was trying to construct a signer used directly rather than using the SSH agent - is it possible you have `SDC_KEY_MATERIAL=` set in your environment?

**Comment by siepkes** [comment]
@jen20 That was it! `TRITON_KEY_MATERIAL` was still in my environment which apparently the Triton provider started to pick up after 0.9.5 and caused problems. Sorry for the noise!

**Comment by jen20** [comment]
No worries - happy this is fixed!
